language: bash
services:
  - docker
script:
  - make image flavor=$FLAVOR nginx_version=$NGINX_VERSION
  - make test flavor=$FLAVOR nginx_version=$NGINX_VERSION
  - |
    if [[ "${TRAVIS_BRANCH}" != "master" || "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
      echo "only push on docker hub on master branch or tags"
      exit 0
    fi
    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    if [[ ! -z "$TRAVIS_TAG" ]]; then
      docker tag tsuru/nginx-${FLAVOR}:${NGINX_VERSION} tsuru/nginx-${FLAVOR}:${NGINX_VERSION}-${TRAVIS_TAG}
    else
      docker push tsuru/nginx-${FLAVOR}:${NGINX_VERSION}
    fi
env:
  global:
    - secure: c2jbo4LdwlTIT2eKdhWCMV7WREyDoRjRQs3AJkRddb1cyvvkuuDXkIu5elzbesuNyFq8g2YLrBv3hk65eBz0lH7+/ASCPF+F9uHZr9jWv1+oUJRcVueW8L+5se+KsbyAF718s+HiUr8lWNdsuZTFfRutngZfYKMBJbq82Xr4dCSHkyyFTUcNaBvJBSmGO1r4M9vF69uXhhl/IcAmMrOq8bM4rRD0AWM6YQ8DkYNTrnzcmcxc6Ljn7/xlCEBc1azEI9HdU3m+7W6MsLmcS9b3eUhGLzQ4cQ6qvZH5m25ZGEXs0Ae+X2RqRmD5+bsi5YPEDggCmbGsaC23ZwZ3prJeWPGP7/SycxNtSCO1yq+JgbTkNfL4zjxPUEBxpMpSPFEbSblDoKUjE8XzDTzeLsSeGfFxVCRrG05HOgUHW5epV2hJNEcTeGoMabC5IXt3rBDyzxw7pk2KqiR7xV7E5rj4nrlSmjWtKX9deQIpO2N3U53pLSmF8mzXBT0T9GviHnmFqfpV0kWuvvpbDa90Zk4thPL21lDdcPBS1NATYYN20071oRLntS1GsWeeEhjBYCQbrmHDoyBxf5hoxvt75omDsLaha7IVjOt9Gt3Vc46AyVRjgvF/9JazznRb8xRrL1JU4iIUUgH9hVtMleWwrgsT7hUE0Pom0qAgOEwdgKqmYBo=
  matrix:
    - FLAVOR=tsuru NGINX_VERSION=1.14.0
    - FLAVOR=tsuru NGINX_VERSION=1.15.0
matrix:
  fast_finish: true
notifications:
  slack:
    rooms:
      secure: GHnLu+xiDqsJf9DaBXjVTsBDomVD3ty/Fsqq7NoMBhYb6M/Asqx68O6qdoch9ZPakaeQZoDvN6RYZrhS8+8+IP8sOEWchglGJpTHA8ivh7b0e8GXVRieAT+0NJsznGSGt+iiWkcMNJsy+zCVPfL8jhqut/2GjZOVra839UG7JqBmFy4UQu/yxgg8sOm9SoyXZ5N6reOIFGRhly2zzVKtVjfvq+jiFRkNoEB0t9eYvKquC6WkbEadJ6vHkGpcpvYjv1WRvSEYGygBTLwBoxTr7ko9zCGRusJ1rtWu+r4iuvQH5g8k9ZZAE3tVtumlaRT/vdMlLk2FQEUqfC41ZudUp5gkKRosw00YnVsg5ItcPtuPU11UVGLTvBvAlRh2EhiGicWo8fwszfiqt0lAMEGtRJbdAFZTU86UfKsgURHfByOpzlGnOB+Q/SFYJrFdYqvABgNNOYmeNy5pbVooHHVyPpRo4xR8+yMKinYzbN7g6LbU+Msh7ecWe3hQWGFWBpz8gCOL7IxgIhLIzovNDTFvdw7RXncTtDloqJ+CWt5VnxBlcs381B2tAUlt4uqpqTC4jraVxIRHqKYCH37/r9xojXzUv0peB3CAre1Y164aA38U5S5hN3ylyD66o5kbWF8Eyz5k9tF6bEdYdVibgn/FHwM6sJjKUu+GMviQXq1P7Kc=
